window.onload=function(){
	$(".b").mouseover(function(){
		$(".boxli").show();
	});
	$(".c").mouseover(function(){
		$(".boxli").show();
	});
	$(".xiala").mouseover(function(){
		$(".boxli").show();
	});
	$(".b").mouseout(function(){
		$(".boxli").hide();
	});
	$(".c").mouseout(function(){
		$(".boxli").hide();
	});
	$(".xiala").mouseout(function(){
		$(".boxli").hide();
	});
	$(".floatshow").click(function(){
		$(".floatshow").hide();
		$(".float").show();
	});
	$(".float>.title>span>img").click(function(){
		$(".floatshow").show();
		$(".float").hide();
	});
	$(".chanpingfenlei>div").click(function(){
		$(this).parent().children("ul").toggle();
		$(this).toggleClass("chanpingfenleishouqi");  
	});
	$(".chanpingfenlei>ul>li").click(function(){
		$(this).parent("ul").toggle();
		$(this).parent().parent().children("div").toggleClass("chanpingfenleishouqi"); 
	});
	$(".xiala_anniu").click(function(){
		$(".li_yanse").css("height","321.1px");
		$(".xiala_anniu").hide();
	});
}